### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by LarryIVC** [CarlosIgreda/Portfolio-setup-and-mobile-first#11]
### **@CarlosIgreda, you make good work:**
Could you consider reviewing the next piece of code, where I found a bug?

![image](https://user-images.githubusercontent.com/110146573/226085862-edd02ea6-3cd6-4e00-8867-c177dacd290b.png)

In the statement, the counter i should not include the upper bound because the count starts at 0.

Happy coding 😄

**Comment by CarlosIgreda** [comment]
Thanks for your feedback @LarryIVC. I've already done the change 🤓.

![tufoin](https://media.giphy.com/media/xUNda5RSVWLzb5BET6/giphy.gif)
