### ISSUE TITLE
Pop Up

### ISSUE THREAD

**Issue by HFG43** [CarlosIgreda/Portfolio-setup-and-mobile-first#9]
First of all Congratulations! 🎉 you are making a great job!!! We can see you put a lot of effort into this project, and somehow you are setting new standards on how to do things efficiently!

Here are some optional Suggestions 💡

- [x] Just some comments about DRY Code. You can delete your Media Queries, as you are not going to be needing them anymore.
- [x] Make sure to just leave the code you are actually using for the project.

Keep going with this good practice and happy coding...👏👏😎

**Comment by CarlosIgreda** [comment]
Thanks for your feedback @HFG43. I really appreciated and I will consider this to enhance my code. 🤓

**Comment by CarlosIgreda** [comment]
Thanks for your feedback @HFG43. I've already done the changes 🤓.

![tufoin](https://media.giphy.com/media/xUNda5RSVWLzb5BET6/giphy.gif)
